PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX schema: <http://schema.org/>
PREFIX geo: <http://www.opengis.net/ont/geosparql#>
PREFIX fixo3: <http://fixo3.eu/vocab/>

SELECT ?obsId ?obsLabel ?obsTitle ?obsComment ?obsLocation
WHERE {
  ?obsId rdf:type sosa:Platform .
  ?obsId rdfs:label ?obsLabel .
  ?obsId dc:title ?obsTitle .
  ?obsId rdfs:comment ?obsComment .
  ?obsId schema:location [ 
    geo:hasGeometry [ 
      geo:asWKT ?obsLocation 
    ] 
  ] .
  
  FILTER (datatype(?obsLocation) = geo:wktLiteral)
}
ORDER BY ?obsLabel