PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>

CONSTRUCT {
  ?obsId rdf:type sosa:Platform .
  ?obsId rdfs:label ?obsLabel .
  ?obsId dc:title ?obsTitle .
}
WHERE {
  ?obsId rdf:type sosa:Platform .
  ?obsId rdfs:label ?obsLabel .
  ?obsId dc:title ?obsTitle .
}